export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_LOADING = "GET_PRODUCTS_LOADING";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";

export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_LOADING = "GET_CATEGORY_LOADING";
export const GET_CATEGORY_FAIL = "GET_CATEGORY_FAIL";

export const SET_UPDATED_DATA_SUCCESS = "SET_UPDATED_DATA_SUCCESS";
export const SET_UPDATED_DATA_LOADING = "SET_UPDATED_DATA_LOADING";
export const SET_UPDATED_DATA_FAIL = "SET_UPDATED_DATA_FAIL";
