export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_LOADING = "GET_PRODUCTS_LOADING";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";

export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_LOADING = "GET_CATEGORY_LOADING";
export const GET_CATEGORY_FAIL = "GET_CATEGORY_FAIL";

export const GET_CART_DETAILS_SUCCESS = "GET_CART_DETAILS_SUCCESS";
export const GET_CART_DETAILS_LOADING = "GET_CART_DETAILS_LOADING";
export const GET_CART_DETAILS_FAIL = "GET_CART_DETAILS_FAIL";
